/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTB23 (number 69), J1[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CTRL_PWR_MR_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CTRL_PWR_MR_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CTRL_PWR_MR_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CTRL_PWR_MR_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CTRL_PWR_MR_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC2 (number 72), J1[14]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CTRL_DIR_MR_2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_MR_2_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CTRL_DIR_MR_2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_MR_2_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CTRL_DIR_MR_2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC3 (number 73), J1[16]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CTRL_DIR_ML_2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_ML_2_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CTRL_DIR_ML_2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_ML_2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CTRL_DIR_ML_2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC9 (number 81), J1[9]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CTRL_PWR_ML_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CTRL_PWR_ML_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CTRL_PWR_ML_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CTRL_PWR_ML_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CTRL_PWR_ML_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTC5 (number 77), J1[15]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CTRL_DIR_ML_1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_ML_1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CTRL_DIR_ML_1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_ML_1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CTRL_DIR_ML_1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC7 (number 79), J1[13]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CTRL_DIR_MR_1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_MR_1_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CTRL_DIR_MR_1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CTRL_DIR_MR_1_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CTRL_DIR_MR_1_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC16 (number 90), J1[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SNS_TRIGGER_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SNS_TRIGGER_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SNS_TRIGGER_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SNS_TRIGGER_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SNS_TRIGGER_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC1 (number 71), J1[5]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ECHO_DETECT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ECHO_DETECT_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ECHO_DETECT_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
